name: Continous Integration

on:
  push:
    branches: [ main ]

jobs:

  simpleTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependences
        run: npm install      
      - name: Run test
        run: |
          npm start &
          sleep 2000      
          npm test